spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
      jdbc:
        non_contextual_creation: true
server:
  port: 8077

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: song8420
      driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
#      table-prefix: BATCH_  # 테이블 프리픽스(기본 BATCH_)
    job:
      names: ${job.name:NONE}
#      enabled: false # 기본실행 안되게
